name: Publish to NPM

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          yarn install
          yarn build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  
  
  publish-to-npm:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '15.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install and Build
        run: |
          yarn install
          yarn prepub
      - name: publish
        run: |
          cd npm && npm publish
          dir
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  
    
  tag-version:
    runs-on: ubuntu-latest
    needs: publish-to-npm
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Version
        run: |
          PACKAGE_VERSION=$(cat package.json \| grep \"version\" \| head -1 \| awk -F: '{ print $2 }' \| sed 's/[",]//g' \| tr -d '[[:space:]]')

    - name: Add Tag
      run: |
        git tag v$PACKAGE_VERSION
        git push --tags